### ISSUE TITLE
Enhancement: Not use Tutorial as first song

### ISSUE THREAD

**Issue by DoomEternal** [brightfyregit/High-Effort-Mod-Template#1]
A suggestion I have is making it so it's NOT tutorial. For me the camera movement is pretty off and then whenever I use my own custom sprites as the opponent- then the camera will just go bizzare and point beyond the opponent. I think it would be so much easier to work with if it was something as basic as Dadbattle so that I would have to worry less about sprite issues and weird camera movement.
![Screenshot 2021-07-20 202846](https://user-images.githubusercontent.com/85465645/126426262-8eed52ff-6eef-4da3-8c45-9741adfd8ef6.png)

**Comment by brightfyregit** [comment]
this isn't for asset replacement, this is a template that you can use to start a "High effort mod", then modify with code
